"%curler7_user.model.group.class%":
  properties:
    id:
      identifier: true
  collectionOperations:
    get: ~
    post:
      validation_groups: ['Default', 'post']
  itemOperations:
    get: ~
    put:
      validation_groups: ['Default', 'put']
    delete:
      validation_groups: ['delete']
