"%curler7_user.model.user.class%":
  properties:
    id:
      identifier: true
  collectionOperations:
    get: ~
    post:
      validation_groups: ['Default', 'post']
      security_post_denormalize: 'is_granted("POST", object)'
    register:
      method: POST
      path: /users/register
      validation_groups: ['Default', 'register']
    login_link:
      method: POST
      path: /users/login-link
      validation_groups: ['Default', 'login_link']
      controller: curler7_user.controller.login_link
  itemOperations:
    get:
      security: 'is_granted("GET", object)'
    put:
      validation_groups: ['Default', 'put']
      security: 'is_granted("PUT", object)'
    delete:
      validation_groups: ['Default', 'delete']
      security: 'is_granted("DELETE", object)'