Curler7\UserBundle\Model\AbstractUser:
  attributes:
    id:
      groups: ['user:read', 'user:post']
    username:
      groups: ['user']
    email:
      groups: ['user']
    lastLogin:
      groups: ['user:read']
    enabled:
      groups: ['super_admin:user']
    roles:
      groups: ['user:read', 'super_admin:user:write']
    plainPassword:
      groups: ['user:write']
    groups:
      groups: ['super_admin:user']
