Curler7\UserBundle\Model\Group:
  properties:
    name:
      - NotBlank:
          message: curler7_user.group.name.not_blank
          groups: [ 'post', 'put' ]
      - Length:
          max: 180
          maxMessage: curler7_user.group.name.length.max
          groups: [ 'post', 'put' ]
