Curler7\UserBundle\Model\User:
  properties:
    username:
      - NotBlank:
          message: curler7_user.user.username.not_blank
          groups: [ 'post', 'put' ]
      - Length:
          max: 180
          maxMessage: curler7_user.user.username.length.max
          groups: [ 'post', 'put' ]
        
    email:
      - NotBlank:
          message: curler7_user.user.email.not_blank
          groups: [ 'post', 'put' ]
      - Email:
          message: curler7_user.user.email.email
