Curler7\UserBundle\Model\AbstractUser:
  properties:
    username:
      - NotBlank:
          message: curler7_user.user.username.not_blank
          groups: ['post', 'put', 'register']
      - Length:
          max: 180
          maxMessage: curler7_user.user.username.length.max
          groups: ['post', 'put', 'register']
        
    email:
      - NotBlank:
          message: curler7_user.user.email.not_blank
          groups: ['post', 'put', 'register', 'login_link']
      - Email:
          message: curler7_user.user.email.email
          groups: ['post', 'put', 'register', 'login_link']
      - Length:
          max: 180
          maxMessage: curler7_user.user.email.length.max
          groups: ['post', 'put', 'register', 'login_link']
    enabled:
      - Curler7\UserBundle\Validator\LastSuperAdminUser:
          groups: ['put', 'delete']