Curler7\UserBundle\Model\AbstractUser:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: usernameCanonical
        errorPath: username
        message: curler7_user.user.username.unique_entity
        groups: ['post', 'put', 'register']
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: emailCanonical
        errorPath: email
        message: curler7_user.user.email.unique_entoty
        groups: ['post', 'put', 'register']
