Curler7\UserBundle\Model\AbstractUser:
  constraints:
    - Curler7\UserBundle\Validator\LastSuperAdminUser:
        groups: ['put', 'delete']
  properties:
    username:
      - NotBlank:
          message: curler7_user.user.username.not_blank
          groups: ['post', 'put', 'register']
      - Length:
          min: 3
          max: 180
          minMessage: curler7_user.user.username.length.min
          maxMessage: curler7_user.user.username.length.max
          groups: ['post', 'put', 'register']
        
    email:
      - NotBlank:
          message: curler7_user.user.email.not_blank
          groups: ['post', 'put', 'register', 'login_link']
      - Email:
          message: curler7_user.user.email.email
          groups: ['post', 'put', 'register', 'login_link']
      - Length:
          max: 180
          maxMessage: curler7_user.user.email.length.max
          groups: ['post', 'put', 'register', 'login_link']

    plainPassword:
      - NotBlank:
          message: curler7_user.user.password.not_blank
          groups: ['post', 'register']
      - Length:
          min: 8
          max: 180
          minMessage: curler7_user.user.password.length.min
          maxMessage: curler7_user.user.password.length.max
          groups: ['post', 'put', 'register']